### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/things/pio/PeripheralManager;

### ISSUE THREAD

**Issue by isaisachen** [androidthings/sample-tensorflow-imageclassifier#13]
Tried to run the sample on Rasberry Pi flashed with Android Things and got this exception. Any idea?

(Not sure if related, but I failed to make my device's speaker work with TextToSpeech and thus wanted to try this sample. So it's possible there's some missing setup steps. But I have no clue right now) 

E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.androidthings.imageclassifier, PID: 2191
                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/things/pio/PeripheralManager;
                                                     at com.example.androidthings.imageclassifier.ImageClassifierActivity.initPIO(ImageClassifierActivity.java:108)
                                                     at com.example.androidthings.imageclassifier.ImageClassifierActivity.init(ImageClassifierActivity.java:95)
                                                     at com.example.androidthings.imageclassifier.ImageClassifierActivity.onCreate(ImageClassifierActivity.java:90)
                                                     at android.app.Activity.performCreate(Activity.java:7000)
                                                     at android.app.Activity.performCreate(Activity.java:6991)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                     at android.os.Handler.dispatchMessage(Handler.java:106)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.things.pio.PeripheralManager" on path: DexPathList[[zip file "/system/framework/com.google.android.things.jar", zip file "/data/app/com.example.androidthings.imageclassifier-VRljk3yGxv0DgffFbpgFRw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.androidthings.imageclassifier-VRljk3yGxv0DgffFbpgFRw==/lib/arm, /data/app/com.example.androidthings.imageclassifier-VRljk3yGxv0DgffFbpgFRw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                     at com.example.androidthings.imageclassifier.ImageClassifierActivity.initPIO(ImageClassifierActivity.java:108) 
                                                     at com.example.androidthings.imageclassifier.ImageClassifierActivity.init(ImageClassifierActivity.java:95) 
                                                     at com.example.androidthings.imageclassifier.ImageClassifierActivity.onCreate(ImageClassifierActivity.java:90) 
                                                     at android.app.Activity.performCreate(Activity.java:7000) 
                                                     at android.app.Activity.performCreate(Activity.java:6991) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by isaisachen** [comment]
Answer myself. Need to upgrade the Android Things OS to 0.7 dev preview.

**Comment by csukerdam** [comment]
Hey, can you explain me how to upgrade Android Things?
I am new and a little bit lost.
Thenk you for helping me!!
