### ISSUE TITLE
java.lang.IllegalArgumentException: No intent supplied

### ISSUE THREAD

**Issue by sonagarajan** [androidthings/sample-tensorflow-imageclassifier#9]
When I run
**adb shell am start**
I get
`java.lang.IllegalArgumentException: No intent supplied
        at android.content.Intent.parseCommandArgs(Intent.java:6682)
        at com.android.server.am.ActivityManagerShellCommand.makeIntent(ActivityManagerShellCommand.java:278)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:328)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:141)
        at android.os.ShellCommand.exec(ShellCommand.java:96)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15014)
        at android.os.Binder.shellCommand(Binder.java:594)
        at android.os.Binder.onTransact(Binder.java:492)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4243)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2919)
        at android.os.Binder.execTransact(Binder.java:697)`

**Comment by daj** [comment]
The command listed in the README needs to be run on one line, like so:
```
adb shell am start com.example.androidthings.imageclassifier/.ImageClassifierActivity
```
I've created pull request https://github.com/androidthings/sample-tensorflow-imageclassifier/pull/10 to fix the documentation.
